namespace CX.Engine.DeploymentHelper;

public static class Vars
{
    public const string ENVIRONMENT = "ENVIRONMENT";
    public const string LANGFUSE_HOST = "LANGFUSE_HOST";
    public const string LANGFUSE_PUBLIC_KEY = "LANGFUSE_PUBLIC_KEY";
    public const string LANGFUSE_SECRET_KEY = "LANGFUSE_SECRET_KEY";
    public const string LANGFUSE_TRACE_IMPORTS = "LANGFUSE_TRACE_IMPORTS";
    public const string OPENAI_API_KEY = "OPENAI_API_KEY";
    public const string PINECONE_API_KEY = "PINECONE_API_KEY";
    public const string PINECONE_INDEX_NAME = "PINECONE_INDEX_NAME";
    public const string PINECONE_NAMESPACE = "PINECONE_NAMESPACE";
    public const string POSTGRESQL_DB_PASSWORD = "POSTGRESQL_DB_PASSWORD";
    public const string POSTGRESQL_DB_SERVER = "POSTGRESQL_DB_SERVER";
    public const string POSTGRESQL_DB_USER = "POSTGRESQL_DB_USER";
    public const string CONTEXTAI_API_KEY = "CONTEXTAI_API_KEY";
    public const string CONTEXTAI_HOST = "CONTEXTAI_HOST";
    public const string AZURE_TRANSLATOR_API_KEY = "AZURE_TRANSLATOR_API_KEY";
    public const string IMPORTER_EXTRACT_IMAGES = "IMPORTER_EXTRACT_IMAGES";
    public const string IMPORTER_TEXT_PROCESSOR_1 = "IMPORTER_TEXT_PROCESSOR_1";
    public const string IMPORTER_DEFAULT_ATTACH_PAGE_IMAGES = "IMPORTER_DEFAULT_ATTACH_PAGE_IMAGES";
    public const string IMPORTER_DEFAULT_ATTACH_TO_SELF = "IMPORTER_DEFAULT_ATTACH_TO_SELF";
    public const string IMPORTER_TRAIN_CITATIONS = "IMPORTER_TRAIN_CITATIONS";
    public const string IMPORTER_PREFER_IMAGE_TEXT_EXTRACTION = "IMPORTER_PREFER_IMAGE_TEXT_EXTRACTION";
    public const string GPT4_VISION_SYSTEM_PROMPT = "GPT4_VISION_SYSTEM_PROMPT";
    public const string GPT4_VISION_QUESTION = "GPT4_VISION_QUESTION";
    public const string EMBEDDINGS_MODEL_NAME = "EMBEDDINGS_MODEL_NAME";
    public const string AZURE_CONTENT_SAFETY_API_KEY = "AZURE_CONTENT_SAFETY_API_KEY";
    public const string AZURE_CONTENT_SAFETY_ENDPOINT = "AZURE_CONTENT_SAFETY_ENDPOINT";
    public const string ARCHIVE_ATTACHMENTS_BASE_URL = "ARCHIVE_ATTACHMENTS_BASE_URL";
    public const string LINE_SPLITTER_SEGMENT_TOKEN_LIMIT = "LINE_SPLITTER_SEGMENT_TOKEN_LIMIT";
    public const string ASSISTANT_MIN_SIMILARITY = "ASSISTANT_MIN_SIMILARITY";
    public const string ASSISTANT_CUTOFF_CONTEXT_TOKENS = "ASSISTANT_CUTOFF_CONTEXT_TOKENS";
    public const string ASSISTANT_CHAT_PROMPT = "ASSISTANT_CHAT_PROMPT";
    public const string ASSISTANT_CONTEXTUALIZE_PROMPT = "ASSISTANT_CONTEXTUALIZE_PROMPT";
    public const string ASSISTANT_TEXT_PROCESSOR_1 = "ASSISTANT_TEXT_PROCESSOR_1";
    public const string ASSISTANT_TEXT_PROCESSOR_2 = "ASSISTANT_TEXT_PROCESSOR_2";

    public const string STUCTURED_DATA_API_KEY = "STUCTURED_DATA_API_KEY";
    public const string STUCTURED_DATA_API_SECRET = "STUCTURED_DATA_API_SECRET";

    public const string WEELEE_CLIENT_ID = "WEELEE_CLIENT_ID";
    public const string WEELEE_CLIENT_SECRET = "WEELEE_CLIENT_SECRET";
    public const string WEELEE_USERNAME = "WEELEE_USERNAME";
    public const string WEELEE_PASSWORD = "WEELEE_PASSWORD";
    public const string WEELEE_REQUEST_URL = "WEELEE_REQUEST_URL";
}