name: $(date:yyyyMMdd)-$(SourceBranchName)-$(BuildID)
trigger: 
  batch: true
  branches:
    include:
    - main
    - development
    - releases/**
  paths:
    include:
      - src/VectorMind.Configuration/*

resources:
  repositories:
    - repository: dashboard-server
      type: git
      name: dashboard-server
      ref: development

variables:
  system.debug: true

stages:
- stage: Versioning
  jobs:
  - template: templates/jobs-versioning.yml

- stage: BuildAndPackage
  variables:
    Version: $[ stageDependencies.Versioning.SemVerCalculation.outputs['outputVars.Version'] ]
  dependsOn: Versioning
  jobs:

  - template: templates/jobs-package-helm-chart-as-artifact.yml
    parameters:
      Version: $(Version)
      ChartPath: src/VectorMind.Configuration/charts/configuration
     
  - template: templates/jobs-build-microservice.yml
    parameters:
      Version: $(Version)
      job:
        name: BuildMicroService
      ProjPath: 'src/VectorMind.Configuration/VectorMind.Configuration.Api'
      DockerImg: 'server/vector.mind.configuration.api'

  - template: templates/jobs-git-tag.yml
    parameters:
      checkout: dashboard-server

