apiVersion: v1
kind: Service
metadata:
  name: {{ include "cx-container-server.chart.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "cx-container-server.chart.name" . }}
    helm.sh/chart: {{ include "cx-container-server.chart.nameAndVersion" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cx-container-server.chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}