version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.csharp
    environment:
      POSTGRES_CONNECTION_STRING: Host=db;Username=postgres;Password=postgres;Database=postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"
volumes:
  db-data: