(function(){
  'use strict';

  window.WB = window.WB || {};

  window.WB.examples = {
    linear: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:80},{id:'n2',type:'Task',title:'Task A',x:320,y:80},{id:'n3',type:'Task',title:'Task B',x:560,y:80},{id:'n4',type:'End',title:'End',x:800,y:80}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'out'},{id:'e3',from:'n3',to:'n4',type:'success',port:'out'}] }),
    decision: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:120},{id:'n2',type:'If',title:'Check',x:320,y:120},{id:'n3',type:'Task',title:'Yes path',x:560,y:40},{id:'n4',type:'Task',title:'No path',x:560,y:200},{id:'n5',type:'End',title:'End',x:800,y:120}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'true'},{id:'e3',from:'n2',to:'n4',type:'success',port:'false'},{id:'e4',from:'n3',to:'n5',type:'success',port:'out'},{id:'e5',from:'n4',to:'n5',type:'success',port:'out'}] }),
    parallel: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:120},{id:'n2',type:'Task',title:'Fan-out',x:320,y:120},{id:'n3',type:'Task',title:'Worker A',x:560,y:40},{id:'n4',type:'Task',title:'Worker B',x:560,y:200},{id:'n5',type:'Task',title:'Join',x:800,y:120},{id:'n6',type:'End',title:'End',x:1040,y:120}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'out'},{id:'e3',from:'n2',to:'n4',type:'success',port:'out'},{id:'e4',from:'n3',to:'n5',type:'success',port:'out'},{id:'e5',from:'n4',to:'n5',type:'success',port:'out'},{id:'e6',from:'n5',to:'n6',type:'success',port:'out'}] }),
    retry: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:120},{id:'n2',type:'Task',title:'Try',x:320,y:120},{id:'n3',type:'Task',title:'Repeat',x:560,y:120},{id:'n4',type:'End',title:'End',x:800,y:120}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'out'},{id:'e3',from:'n3',to:'n2',type:'success',port:'out'},{id:'e4',from:'n3',to:'n4',type:'success',port:'out'}] }),
    timer: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:120},{id:'n2',type:'Task',title:'Wait',x:320,y:120},{id:'n3',type:'End',title:'End',x:560,y:120}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'out'}] }),
    api: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:120},{id:'n2',type:'Task',title:'HTTP GET',x:320,y:120},{id:'n3',type:'Switch',title:'Status switch',x:560,y:120},{id:'n4',type:'Task',title:'Handle 200',x:800,y:40},{id:'n5',type:'Task',title:'Handle 500',x:800,y:200},{id:'n6',type:'End',title:'End',x:1040,y:120}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'out'},{id:'e3',from:'n3',to:'n4',type:'success',port:'GET'},{id:'e4',from:'n3',to:'n5',type:'success',port:'DELETE'},{id:'e5',from:'n4',to:'n6',type:'success',port:'out'},{id:'e6',from:'n5',to:'n6',type:'success',port:'out'}] }),
    error: ()=>({ nodes:[{id:'n1',type:'Start',title:'Start',x:80,y:120},{id:'n2',type:'Task',title:'Risky op',x:320,y:120},{id:'n3',type:'End',title:'End',x:560,y:120}], edges:[{id:'e1',from:'n1',to:'n2',type:'success',port:'out'},{id:'e2',from:'n2',to:'n3',type:'success',port:'out'}] })
  };
})();
